import React, { useState } from 'react';
import { 
  AlertTriangle, 
  Download, 
  FileText, 
  CheckCircle, 
  Clock,
  Phone,
  Users
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/Card';
import { Button } from '../../../components/ui/Button';
import { toast } from '../../../components/ui/Toaster';

const BreachNotificationViewer: React.FC = () => {
  const [activeSection, setActiveSection] = useState<string>('overview');

  const downloadTemplate = () => {
    const templateContent = `PRIVACY BREACH NOTIFICATION TEMPLATE
Generated by CyberCorrect™ Privacy Platform

INCIDENT OVERVIEW
Incident ID: [To be completed - Generate unique incident identifier, e.g., INC-YYYY-MMDD-001]
Date Detected: [To be completed - Date and time when the breach was first detected]
Detection Method: [To be completed - How the breach was discovered: automated monitoring, employee report, third-party notification, etc.]
Incident Type: [To be completed - Classify as: Confidentiality breach, Integrity breach, Availability breach, or combination]

AFFECTED DATA
Types of Personal Data Involved:
□ Contact information (names, addresses, phone numbers, email addresses)
□ Financial information (credit card numbers, bank account details, payment information)
□ Identity information (Social Security Numbers, passport numbers, driver's license numbers)
□ Health information (medical records, health insurance information, biometric health data)
□ Biometric data (fingerprints, facial recognition data, voiceprints)
□ Special category data (race, religion, political opinions, sexual orientation, genetic data)
□ Other: [To be completed - Specify any other types of personal data involved]

Number of Affected Individuals: [To be completed - Exact number or estimated range of affected individuals]
Geographic Scope: [To be completed - List all countries/regions where affected individuals are located]

BREACH DETAILS
How the Breach Occurred: [To be completed - Provide detailed description of how the breach occurred, including technical details, attack vectors, and sequence of events]
Security Measures Bypassed: [To be completed - Describe what security protections failed or were bypassed: encryption, access controls, firewalls, authentication mechanisms, etc.]
Access Gained: [To be completed - Specify what systems, databases, or data were accessed, modified, or exfiltrated]
Duration of Breach: [To be completed - Provide exact or estimated timeframe: from [start date/time] to [end date/time]]

IMMEDIATE RESPONSE ACTIONS TAKEN
□ Containment measures implemented
□ Breach source identified and secured
□ Affected systems isolated
□ Incident response team activated
□ Law enforcement notified (if applicable)
□ Insurance company notified
□ Forensic investigation initiated
[To be completed - Document any additional immediate response actions taken]

RISK ASSESSMENT
Likelihood of Harm to Individuals:
□ Low - Minimal risk of harm to individuals
□ Medium - Some risk of identity theft, fraud, or other harm
□ High - Significant risk of harm to individuals

Severity of Potential Consequences:
□ Low - Minor inconvenience or annoyance
□ Medium - Financial loss, identity theft, or moderate harm possible
□ High - Substantial harm likely, including significant financial loss, discrimination, or physical harm

REGULATORY NOTIFICATIONS

GDPR Notification (if applicable):
□ Supervisory authority notified within 72 hours of becoming aware of the breach
□ Individual notification sent (if high risk to individuals' rights and freedoms)
Authority Notified: [To be completed - Name of supervisory authority, e.g., ICO (UK), CNIL (France), etc.]
Notification Date: [To be completed - Date and time of notification to supervisory authority]
Reference Number: [To be completed - Reference number provided by supervisory authority]

CCPA Notification (if applicable):
□ California Attorney General notified (if breach affects 500+ California residents)
□ Individual notification provided to affected California residents
Notification Method: [To be completed - Email, mail, website posting, or combination]
Notification Date: [To be completed - Date when notifications were sent]

Other Jurisdictions:
[To be completed - List other applicable notification requirements: PIPEDA (Canada), LGPD (Brazil), SHIELD Act (New York), etc. Document notification dates, authorities contacted, and reference numbers]

INDIVIDUAL NOTIFICATION
Notification Required: □ Yes □ No
Reason if No: [If no notification required, provide detailed justification explaining why notification is not necessary, including risk assessment]

If Yes:
Notification Method: □ Email □ Mail □ Phone □ Website posting □ Combination
Date Sent: [To be completed - Date when individual notifications were sent]
Number of Individuals Notified: [To be completed - Exact number of individuals who received notification]

NOTIFICATION CONTENT CHECKLIST
□ Nature of breach described in clear and plain language
□ Categories of data involved specified
□ Likely consequences explained
□ Measures taken to address breach outlined
□ Measures recommended for individuals included (e.g., change passwords, monitor accounts)
□ Contact information provided for data protection officer or privacy team

REMEDIATION MEASURES
Immediate Actions:
□ Change passwords/credentials for affected accounts
□ Patch security vulnerabilities that enabled the breach
□ Enhance monitoring and detection capabilities
□ Additional staff training on security and privacy
[To be completed - Document any additional immediate remediation measures]

Long-term Improvements:
□ Security control enhancements (e.g., stronger encryption, multi-factor authentication)
□ Process improvements (e.g., access review procedures, data minimization)
□ Technology upgrades (e.g., security tools, monitoring systems)
□ Policy updates (e.g., incident response plan, data protection policies)
[To be completed - Document any additional long-term improvements planned]

LESSONS LEARNED
Root Cause: [To be completed - Identify the primary cause of the breach: technical failure, human error, malicious attack, process failure, etc.]
Contributing Factors: [To be completed - List secondary factors that contributed to the breach: lack of training, insufficient controls, outdated systems, etc.]
Process Improvements: [To be completed - Describe what will be changed to prevent similar breaches in the future]

DOCUMENTATION
□ Incident report completed
□ Evidence preserved (logs, screenshots, forensic data)
□ Timeline documented (chronological sequence of events)
□ Communications logged (internal and external communications)
□ Regulatory correspondence filed
□ Individual notification records maintained

APPROVAL
Prepared by: [To be completed - Name and title of person who prepared this notification]
Date: [To be completed - Date when notification was prepared]
Reviewed by: [To be completed - Name and title of DPO or Privacy Officer who reviewed]
Date: [To be completed - Date of review]
Approved by: [To be completed - Name and title of senior management who approved]
Date: [To be completed - Date of approval]

---
This template ensures comprehensive documentation of privacy breaches and compliance with notification requirements across jurisdictions.
Generated by CyberCorrect™ Privacy Platform
For assistance with breach notification procedures, visit www.cybercorrect.com or contact support.
Generated: ${new Date().toLocaleDateString()}
© ${new Date().getFullYear()} ERMITS LLC. All rights reserved.
    `;

    const blob = new Blob([templateContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `breach-notification-template-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    
    toast.success("Download started", "Breach notification template downloaded successfully");
  };

  const sections = [
    { id: 'overview', title: 'Template Overview', icon: AlertTriangle },
    { id: 'requirements', title: 'Notification Requirements', icon: Clock },
    { id: 'process', title: 'Notification Process', icon: FileText },
    { id: 'compliance', title: 'Compliance Checklist', icon: CheckCircle }
  ];

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="mb-6">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-3xl font-bold mb-2 text-foreground">Breach Notification Template</h1>
            <p className="text-muted-foreground">Comprehensive template for privacy breach notification procedures</p>
          </div>
          <Button onClick={downloadTemplate} variant="destructive">
            <Download className="h-4 w-4 mr-2" />
            Download Template
          </Button>
        </div>
      </div>

      {/* Template Overview */}
      <Card className="mb-6">
        <CardHeader>
          <CardTitle className="flex items-center">
            <AlertTriangle className="h-5 w-5 mr-2 text-destructive" />
            Breach Notification Framework
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            <div className="text-center">
              <div className="bg-destructive/10 dark:bg-destructive/20 p-3 rounded-lg inline-block mb-2">
                <Clock className="h-6 w-6 text-destructive" />
              </div>
              <h3 className="font-semibold text-foreground">72-Hour Rule</h3>
              <p className="text-sm text-muted-foreground">GDPR notification deadline</p>
            </div>
            <div className="text-center">
              <div className="bg-primary/10 dark:bg-primary/20 p-3 rounded-lg inline-block mb-2">
                <Phone className="h-6 w-6 text-primary" />
              </div>
              <h3 className="font-semibold text-foreground">Authority Notification</h3>
              <p className="text-sm text-muted-foreground">Regulatory reporting</p>
            </div>
            <div className="text-center">
              <div className="bg-success/10 dark:bg-success/20 p-3 rounded-lg inline-block mb-2">
                <Users className="h-6 w-6 text-success" />
              </div>
              <h3 className="font-semibold text-foreground">Individual Notice</h3>
              <p className="text-sm text-muted-foreground">Data subject notification</p>
            </div>
            <div className="text-center">
              <div className="bg-accent/10 dark:bg-accent/20 p-3 rounded-lg inline-block mb-2">
                <FileText className="h-6 w-6 text-accent" />
              </div>
              <h3 className="font-semibold text-foreground">Documentation</h3>
              <p className="text-sm text-muted-foreground">Incident records</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Navigation Tabs */}
      <div className="bg-background border-b border-border mb-6 -mx-4 sm:-mx-6 lg:-mx-8 px-4 sm:px-6 lg:px-8">
        <nav className="flex space-x-8">
          {sections.map(section => (
            <button
              key={section.id}
              onClick={() => setActiveSection(section.id)}
              className={`py-4 px-1 border-b-2 font-medium text-sm transition-colors flex items-center ${
                activeSection === section.id
                  ? 'border-destructive text-destructive'
                  : 'border-transparent text-muted-foreground hover:text-foreground'
              }`}
            >
              <section.icon className="w-4 h-4 mr-2" />
              {section.title}
            </button>
          ))}
        </nav>
      </div>

      {/* Section Content */}
      <div className="space-y-6">
        {activeSection === 'overview' && (
          <Card>
            <CardHeader>
              <CardTitle>Breach Notification Requirements</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground mb-4">
                Privacy breach notification requirements vary by jurisdiction but generally require prompt notification 
                to both regulatory authorities and affected individuals when certain criteria are met.
              </p>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <h4 className="font-semibold text-foreground mb-2">Key Notification Triggers:</h4>
                  <ul className="space-y-1 text-sm text-muted-foreground">
                    <li>• Unauthorized access to personal data</li>
                    <li>• Data theft or loss of devices containing personal data</li>
                    <li>• Accidental disclosure to unauthorized parties</li>
                    <li>• System breaches affecting personal data integrity</li>
                  </ul>
                </div>
                <div className="space-y-2">
                  <h4 className="font-semibold text-foreground mb-2">Risk Assessment Factors:</h4>
                  <ul className="space-y-1 text-sm text-muted-foreground">
                    <li>• Types of personal data affected</li>
                    <li>• Number of individuals impacted</li>
                    <li>• Likelihood of harm to individuals</li>
                    <li>• Severity of potential consequences</li>
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {activeSection === 'requirements' && (
          <div className="text-center py-12">
            <Clock className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <h3 className="text-lg font-medium text-foreground mb-2">Notification Requirements</h3>
            <p className="text-muted-foreground">
              Comprehensive guidance on breach notification requirements under GDPR Article 33 and 34, including the 72-hour notification timeline, content requirements, and supervisory authority obligations
            </p>
          </div>
        )}

        {activeSection === 'process' && (
          <div className="text-center py-12">
            <FileText className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <h3 className="text-lg font-medium text-foreground mb-2">Notification Process</h3>
            <p className="text-muted-foreground">
              Step-by-step workflow for managing data breach notifications, from initial detection and assessment to notification execution and documentation
            </p>
          </div>
        )}

        {activeSection === 'compliance' && (
          <div className="text-center py-12">
            <CheckCircle className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <h3 className="text-lg font-medium text-foreground mb-2">Compliance Checklist</h3>
            <p className="text-muted-foreground">
              Detailed checklist to ensure your breach notification process meets all regulatory requirements across GDPR, CCPA, and other applicable privacy regulations
            </p>
          </div>
        )}
      </div>
    </div>
  );
};

export default BreachNotificationViewer;
