import React from 'react';
import { FileText, Download, Eye, Shield, CheckCircle, Users, Building, Calendar, AlertTriangle } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/Card';
import { Button } from '../../../components/ui/Button';

const DpiaTemplateViewer: React.FC = () => {
  const handleDownload = () => {
    // Simulate download functionality
    const content = `DATA PROTECTION IMPACT ASSESSMENT (DPIA)
Generated by CyberCorrect™ Privacy Platform

SECTION 1: PROJECT OVERVIEW
Project Name: [To be completed - Provide the name of the project or processing activity]
Data Controller: [To be completed - Organization name, address, and contact details]
Date of Assessment: [To be completed - Date when the assessment is conducted]
Assessed by: [To be completed - Name and title of the person conducting the assessment]

SECTION 2: DESCRIPTION OF PROCESSING
Nature of Processing: [To be completed - Detailed description of what data processing activities will be performed]
Scope of Processing: [To be completed - Geographic scope, systems involved, data volumes, and operational boundaries]
Context of Processing: [To be completed - Business context, operational environment, and relationship with data subjects]
Purposes of Processing: [To be completed - All purposes for which personal data will be processed, be specific and comprehensive]

SECTION 3: NECESSITY AND PROPORTIONALITY
Lawful Basis: [To be completed - Identify the lawful basis under GDPR Article 6: consent, contract, legal obligation, vital interests, public task, or legitimate interests]
Legitimate Interests: [If using legitimate interests - Describe the legitimate interests pursued, necessity assessment, and balancing test]
Data Minimization: [To be completed - Explain how data collection is limited to what is necessary for the stated purposes]
Purpose Limitation: [To be completed - Describe how data use is restricted to the stated purposes and how this is enforced]

SECTION 4: DATA SUBJECTS AND PERSONAL DATA
Categories of Data Subjects: [To be completed - List all categories, e.g., customers, employees, website visitors, suppliers, partners]
Categories of Personal Data: [To be completed - List all data types, e.g., names, email addresses, IP addresses, financial information, health data]
Special Category Data: [If applicable - List special categories under GDPR Article 9: racial/ethnic origin, political opinions, religious beliefs, health data, biometric data, etc.]
Retention Period: [To be completed - Specify how long data will be retained, retention schedule, and justification for retention periods]

SECTION 5: RISKS TO DATA SUBJECTS
High Risk Factors: [To be completed - Identify factors that increase risk: large-scale processing, automated decision-making, special category data, vulnerable individuals, etc.]
Impact on Data Subjects: [To be completed - Assess potential consequences if risks materialize: identity theft, discrimination, financial loss, reputational damage, etc.]
Likelihood of Risk: [To be completed - Assess probability: low (unlikely), medium (possible), or high (likely)]
Risk Rating: [To be completed - Overall risk level: low, medium, high, or critical - consider both impact and likelihood]

SECTION 6: MEASURES TO ADDRESS RISKS
Technical Measures: [To be completed - List technical safeguards: encryption, access controls, pseudonymization, anonymization, secure storage, backup procedures, etc.]
Organizational Measures: [To be completed - List organizational safeguards: staff training, policies, procedures, audits, data protection by design, privacy impact assessments, etc.]
Data Subject Rights: [To be completed - Explain how rights are protected: access, rectification, erasure, portability, objection, restriction, and automated decision-making]
Consent Mechanisms: [If applicable - Describe consent collection, management, withdrawal procedures, and how consent is documented]

SECTION 7: CONSULTATION AND APPROVAL
DPO Consultation: [To be completed - Document date of consultation, outcome, recommendations provided, and how recommendations were addressed]
Stakeholder Involvement: [To be completed - List all stakeholders consulted (IT, legal, security, business units), their input, and how concerns were addressed]
Supervisory Authority: [If consulted - Document which supervisory authority was consulted, date, reference number, and response received]
Approval Date: [To be completed - Date of final approval, approver name and title, and any conditions attached to approval]

SECTION 8: MONITORING AND REVIEW
Review Schedule: [To be completed - Frequency of reviews: typically annually or when processing activities change significantly]
Monitoring Procedures: [To be completed - Describe ongoing monitoring activities, key metrics to track, and how compliance is verified]
Update Triggers: [To be completed - Events that require DPIA update or reassessment: new processing activities, changes in technology, regulatory changes, incidents, etc.]
Documentation: [To be completed - Describe how DPIA will be maintained, version controlled, stored securely, and made available to relevant parties]

---
This DPIA template is provided by CyberCorrect™ Privacy Platform.
For assistance with completing your DPIA, visit www.cybercorrect.com or contact support.
Generated: ${new Date().toLocaleDateString()}
© ${new Date().getFullYear()} ERMITS LLC. All rights reserved.`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'dpia-template.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="mb-6">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-3xl font-bold mb-2 text-foreground">DPIA Template Viewer</h1>
            <p className="text-muted-foreground">Data Protection Impact Assessment template for GDPR compliance</p>
          </div>
        </div>
      </div>

      {/* Template Overview */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
        <Card className="border-l-4 border-l-primary">
          <CardContent className="p-6">
            <div className="flex items-center space-x-3 mb-3">
              <Shield className="h-8 w-8 text-primary" />
              <div>
                <h3 className="font-semibold text-foreground">GDPR Compliant</h3>
                <p className="text-sm text-muted-foreground">Follows GDPR Article 35 requirements</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-l-4 border-l-success">
          <CardContent className="p-6">
            <div className="flex items-center space-x-3 mb-3">
              <CheckCircle className="h-8 w-8 text-success" />
              <div>
                <h3 className="font-semibold text-foreground">8 Sections</h3>
                <p className="text-sm text-muted-foreground">Comprehensive assessment structure</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-l-4 border-l-accent">
          <CardContent className="p-6">
            <div className="flex items-center space-x-3 mb-3">
              <FileText className="h-8 w-8 text-accent" />
              <div>
                <h3 className="font-semibold text-foreground">Ready to Use</h3>
                <p className="text-sm text-muted-foreground">Download and customize</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Template Content */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center">
              <FileText className="h-5 w-5 mr-2 text-primary" />
              DPIA Template Structure
            </CardTitle>
            <div className="flex items-center space-x-3">
              <Button variant="outline" onClick={handleDownload}>
                <Download className="h-4 w-4 mr-2" />
                Download Template
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="space-y-6">
            {/* Template Sections */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {[
                {
                  section: "1. Project Overview",
                  description: "Basic project information, data controller details, and assessment metadata",
                  icon: Building,
                  color: "text-primary"
                },
                {
                  section: "2. Description of Processing",
                  description: "Nature, scope, context, and purposes of the data processing activities",
                  icon: Eye,
                  color: "text-success"
                },
                {
                  section: "3. Necessity and Proportionality",
                  description: "Lawful basis, legitimate interests, data minimization, and purpose limitation",
                  icon: Shield,
                  color: "text-accent"
                },
                {
                  section: "4. Data Subjects and Personal Data",
                  description: "Categories of data subjects, personal data types, and retention periods",
                  icon: Users,
                  color: "text-warning"
                },
                {
                  section: "5. Risks to Data Subjects",
                  description: "Risk identification, impact assessment, likelihood, and risk rating",
                  icon: AlertTriangle,
                  color: "text-destructive"
                },
                {
                  section: "6. Measures to Address Risks",
                  description: "Technical and organizational measures, data subject rights protection",
                  icon: CheckCircle,
                  color: "text-success"
                },
                {
                  section: "7. Consultation and Approval",
                  description: "DPO consultation, stakeholder involvement, and approval documentation",
                  icon: Users,
                  color: "text-primary"
                },
                {
                  section: "8. Monitoring and Review",
                  description: "Review schedule, monitoring procedures, and update triggers",
                  icon: Calendar,
                  color: "text-accent"
                }
              ].map((item, index) => (
                <Card key={index} className="border hover:shadow-lg transition-shadow">
                  <CardContent className="p-4">
                    <div className="flex items-start space-x-3">
                      <item.icon className={`h-6 w-6 ${item.color} mt-1`} />
                      <div>
                        <h4 className="font-semibold text-foreground mb-2">{item.section}</h4>
                        <p className="text-sm text-muted-foreground">{item.description}</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>

            {/* Usage Instructions */}
            <Card className="bg-primary/5 border-primary/20">
              <CardContent className="p-6">
                <h3 className="font-semibold text-primary mb-2">How to Use This Template</h3>
                <div className="space-y-2 text-sm text-muted-foreground">
                  <p>• Download the template and customize it for your specific processing activities</p>
                  <p>• Complete each section thoroughly, providing detailed information</p>
                  <p>• Conduct the DPIA before beginning any high-risk processing activities</p>
                  <p>• Consult with your Data Protection Officer (DPO) during the assessment</p>
                  <p>• Review and update the DPIA regularly or when processing changes</p>
                  <p>• Keep documentation of the assessment process and outcomes</p>
                </div>
              </CardContent>
            </Card>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default DpiaTemplateViewer;
