import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export interface SSPExportData {
  metadata: {
    exportDate: string;
    version: string;
    organization: string;
    systemName: string;
    classification: string;
  };
  systemInfo: {
    name: string;
    owner: string;
    identifier: string;
    description: string;
    classification: string;
  };
  sections: Array<{
    title: string;
    status: string;
    content: Record<string, unknown>;
  }>;
  controls: Array<{
    id: string;
    title: string;
    description: string;
    status: string;
    priority: string;
    implementation: {
      status: string;
      notes: string;
      lastAssessed: string;
      assessedBy: string;
    };
  }>;
  metrics: {
    totalControls: number;
    implementedControls: number;
    compliancePercentage: number;
  };
}

export const generateSSPPdf = (data: SSPExportData): void => {
  const doc = new jsPDF();
  let y = 20;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(40, 40, 40);
  doc.text('System Security Plan (SSP)', 105, y, { align: 'center' });
  y += 10;

  doc.setFontSize(16);
  doc.text(data.systemInfo.name, 105, y, { align: 'center' });
  y += 15;

  // Metadata
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Organization: ${data.metadata.organization}`, 20, y);
  y += 5;
  doc.text(`Generated: ${new Date(data.metadata.exportDate).toLocaleDateString()}`, 20, y);
  y += 5;
  doc.text(`Classification: ${data.metadata.classification}`, 20, y);
  y += 20;

  // System Information
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text('1. System Information', 20, y);
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.text(`System Name: ${data.systemInfo.name}`, 20, y);
  y += 5;
  doc.text(`System Owner: ${data.systemInfo.owner}`, 20, y);
  y += 5;
  doc.text(`System Identifier: ${data.systemInfo.identifier}`, 20, y);
  y += 5;
  
  // Description with word wrapping
  const descriptionLines = doc.splitTextToSize(`Description: ${data.systemInfo.description}`, 170);
  doc.text(descriptionLines, 20, y);
  y += descriptionLines.length * 5 + 10;

  // Compliance Summary
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text('2. Compliance Summary', 20, y);
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.text(`Total Controls: ${data.metrics.totalControls}`, 20, y);
  y += 5;
  doc.text(`Implemented Controls: ${data.metrics.implementedControls}`, 20, y);
  y += 5;
  doc.text(`Compliance Percentage: ${data.metrics.compliancePercentage}%`, 20, y);
  y += 15;

  // Risk level indicator
  let riskLevel = 'Low Risk';
  let riskColor = [0, 150, 0]; // Green
  
  if (data.metrics.compliancePercentage < 80) {
    riskLevel = 'Moderate Risk';
    riskColor = [0, 100, 200]; // Blue
  }
  if (data.metrics.compliancePercentage < 60) {
    riskLevel = 'High Risk';
    riskColor = [255, 150, 0]; // Orange
  }
  if (data.metrics.compliancePercentage < 40) {
    riskLevel = 'Critical Risk';
    riskColor = [200, 0, 0]; // Red
  }

  doc.setFontSize(12);
  doc.setTextColor(riskColor[0], riskColor[1], riskColor[2]);
  doc.text(`Risk Level: ${riskLevel}`, 20, y);
  y += 20;

  // Controls Table
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text('3. Security Controls', 20, y);
  y += 10;

  const controlsData = data.controls.map(control => [
    control.id,
    control.title.length > 30 ? control.title.substring(0, 30) + '...' : control.title,
    control.status,
    control.priority
  ]);

  doc.autoTable({
    head: [['Control ID', 'Title', 'Status', 'Priority']],
    body: controlsData,
    startY: y,
    headStyles: { fillColor: [60, 100, 240], fontSize: 8 },
    alternateRowStyles: { fillColor: [240, 240, 240], fontSize: 8 }
  });

  // Get last table Y position
  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20;

  // Sections
  data.sections.forEach((section, index) => {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(14);
    doc.setTextColor(40, 40, 40);
    doc.text(`${index + 4}. ${section.title}`, 20, y);
    y += 10;

    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text(`Status: ${section.status}`, 20, y);
    y += 5;
    doc.text('Content details would be included here based on section type.', 20, y);
    y += 15;
  });

  // Footer
  const pageCount = doc.getNumberOfPages ? doc.getNumberOfPages() : 1;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
    doc.text(`Generated by CyberCorrect Privacy Platform`, 20, 285);
    doc.text(`${data.metadata.version}`, 170, 285);
  }

  // Save the PDF
  const filename = `SSP-${data.systemInfo.identifier || 'draft'}-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
};
